//
//  HomeRouter.swift
//  CompanionApp
//
//  Created by Diego Escamilla on 13/03/21.
//  Copyright (c) 2021. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRouterInterface {
    
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: HomeRouterInterface, HomeDataPassing {
    
    // MARK: - Properties
    
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
}
