//
//  HomePresenter.swift
//  CompanionApp
//
//  Created by Diego Escamilla on 13/03/21.
//  Copyright (c) 2021. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresenterInterface {
    func presentHome(response: HomeModels.FetchHome.Response)
}

class HomePresenter: HomePresenterInterface {
    
    // MARK: - Properties
    
    weak var viewController: HomeDisplayInterface?
    
    // MARK: - HomePresenterInterface
    
    func presentHome(response: HomeModels.FetchHome.Response) {
        let viewModel = HomeModels.FetchHome.ViewModel()
        viewController?.displayHome(viewModel: viewModel)
    }
}
