//
//  HomeInteractor.swift
//  CompanionApp
//
//  Created by Diego Escamilla on 13/03/21.
//  Copyright (c) 2021. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol HomeInteractorInterface {
    func fetchHome(request: HomeModels.FetchHome.Request)
}

protocol HomeDataStore {
    
}

class HomeInteractor: HomeInteractorInterface, HomeDataStore {
   
    // MARK: - Properties
    
    var presenter: HomePresenterInterface?
    var worker: HomeWorkerInterface = HomeWorker()
    
    // MARK: - HomeInteractorInterface
    
    func fetchHome(request: HomeModels.FetchHome.Request) {
        
        // Perform network requests here and present afterwards
        
        let response = HomeModels.FetchHome.Response()
        presenter?.presentHome(response: response)
    }
}
